import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';

test('fixed document type settings use the diagnosis template layout', async () => {
  const [html, main, css] = await Promise.all([
    readFile(new URL('../index.html', import.meta.url), 'utf8').then((t) => t.replace(/ data-page-node-id="[^"]*"/g, '')),
    readFile(new URL('../main.js', import.meta.url), 'utf8'),
    readFile(new URL('../style.css', import.meta.url), 'utf8'),
  ]);

  assert.match(main, /const FIXED_DOC_DIAGNOSIS_PREVIEW_IMAGE = 'assets\/mock-diagnosis-liaj045\.png';/);
  assert.match(main, /const FIXED_DOC_HUMAN_DOCK_PREVIEW_IMAGE = 'assets\/mock-human-dock\.png';/);
  await access(new URL('../assets/mock-diagnosis-liaj045.png', import.meta.url));
  await access(new URL('../assets/mock-human-dock.png', import.meta.url));
  await access(new URL('../logo-CWaP-1CB.png', import.meta.url));
  assert.match(html, /class="global-topbar"[\s\S]*<img src="logo-CWaP-1CB\.png" alt="Logo"/);
  assert.doesNotMatch(html, /class="global-nav-logo"/);
  assert.match(html, /class="global-nav-tools"[\s\S]*class="global-nav-collapse"/);
  assert.match(css, /\.global-topbar\s*\{[\s\S]*height:\s*var\(--logo-height\);/);
  assert.match(css, /\.global-logo-area img\s*\{[\s\S]*height:\s*32px;/);
  assert.match(html, /class=\"global-nav-subitem\" @click=\"openReadModelSettings\">\{\{ t\('モデル設定'\) \}\}<\/button>/);
  assert.match(html, /v-model="readModelSettingsVisible"[\s\S]*title="読取モデル設定"[\s\S]*人工確認ルール[\s\S]*readModelHitlRules/);
  assert.match(html, /人工確認ルール[\s\S]*v-for="rule in readModelHitlRules"[\s\S]*\{\{ rule\.label \}\}/);
  assert.match(main, /normal_range_exceeded', label: '正常値範囲を超えています'/);
  assert.match(main, /low_confidence_and_range_exceeded', label: '低信頼度かつ正常値範囲を超えています'/);
  assert.match(main, /hitlRules: \['normal_range_exceeded', 'low_confidence_and_range_exceeded'\]/);
  assert.match(main, /function fieldHasConfiguredNormalCondition\(fieldRule = \{\}\)/);
  assert.match(main, /hitlRules\.includes\('normal_range_exceeded'\)/);
  assert.match(main, /!isQrReadPath[\s\S]*hitlRules\.includes\('low_confidence_and_range_exceeded'\)/);
  assert.match(main, /function toggleReadModelHitlRule\(ruleValue, checked\)/);
  assert.match(html, /@change="toggleReadModelHitlRule\(rule\.value, \$event\)"/);
  assert.doesNotMatch(html, /read-model-hitl-rule-list[\s\S]*disabled/);
  assert.match(css, /\.read-model-hitl-rule-list\s*\{[\s\S]*background:\s*#f5f6f8;/);
  assert.match(css, /\.read-model-hitl-rule-list \.el-checkbox\s*\{[\s\S]*min-height:\s*20px;[\s\S]*height:\s*auto;/);

  assert.match(main, /function openFixedDocSettingsFromMenu\(\) \{\s*const firstType = fixedDocTypeItems\.value\[0\];[\s\S]*openFixedDocSettings\(firstType\.id, 1\);/);
  assert.doesNotMatch(main, /function openFixedDocSettingsFromMenu\(\) \{\s*fixedDocSettingsTarget\.value = '';/);
  assert.match(html, /class="fixed-doc-type-list-pane" :class="\{ 'is-collapsed': fixedDocTypeListCollapsed \}"/);
  assert.match(html, /class="fixed-doc-type-tags-row"[\s\S]*@click="toggleFixedDocTypeList">›<\/button>/);
  assert.match(html, /class="fixed-doc-type-list-title-row"[\s\S]*帳票タイプ[\s\S]*@click="toggleFixedDocTypeList">‹<\/button>[\s\S]*v-model="fixedDocTypeSearch"[\s\S]*placeholder="帳票タイプで検索"[\s\S]*タイプ追加/);
  assert.match(main, /const fixedDocTypeListCollapsed = ref\(false\);/);
  assert.match(main, /function toggleFixedDocTypeList\(\) \{\s*fixedDocTypeListCollapsed\.value = !fixedDocTypeListCollapsed\.value;/);
  assert.match(css, /\.el-button\.el-button--primary:not\(\.is-link\):not\(\.is-plain\):not\(\.is-text\)\s*\{[\s\S]*--el-button-hover-bg-color:\s*var\(--el-color-primary\);[\s\S]*--el-button-hover-border-color:\s*var\(--el-color-primary\);/);
  assert.match(css, /\.fixed-doc-type-list-pane\s*\{[\s\S]*flex:\s*0 0 260px;/);
  assert.match(css, /\.fixed-doc-type-list-pane\.is-collapsed\s*\{[\s\S]*flex-basis:\s*var\(--scene-list-collapsed-width\);/);
  assert.match(css, /\.fixed-doc-type-list-head h2\s*\{[\s\S]*font-size:\s*15px;/);
  assert.match(css, /\.fixed-doc-type-search \.el-input__wrapper\s*\{[\s\S]*min-height:\s*36px;/);
  assert.doesNotMatch(css, /\.fixed-doc-type-list-divider/);
  assert.match(css, /\.fixed-doc-type-add\.el-button\s*\{[\s\S]*min-height:\s*36px;/);
  assert.match(css, /\.fixed-doc-type-item\s*\{[\s\S]*min-height:\s*48px;[\s\S]*border-radius:\s*6px;[\s\S]*padding:\s*0 12px 0 18px;[\s\S]*font-size:\s*15px;/);
  assert.match(html, /v-for="type in fixedDocTypeItemsFiltered"[\s\S]*@click="openFixedDocSettings\(type\.id, 1\)"/);
  assert.match(main, /DOC_TYPE_REGISTRY\.find\(\(item\) => item\.id === '診断書'\)/);
  assert.match(main, /DOC_TYPE_REGISTRY\.find\(\(item\) => item\.id === '人間ドック'\)/);
  assert.match(html, /v-if="fixedDocSettingsTarget" class="fixed-doc-config"/);
  assert.match(html, /v-else class="fixed-doc-type-empty"[\s\S]*帳票タイプを選択してください/);
  assert.doesNotMatch(html, /fixed-doc-type-empty[\s\S]*左側から帳票タイプを選択するか、タイプを追加してください。/);
  assert.match(main, /function createFixedDocType\(\)/);
  assert.match(html, /class="fixed-doc-preview-sheet"/);
  assert.match(html, /class="fixed-doc-preview-image-wrap"/);
  // QR 枠オーバーレイは「読取結果の可視化」としてのみ残す（設定 UI は持たない）
  assert.match(html, /v-if="fixedDocPreviewQrSlots\.length"[\s\S]*class="fixed-doc-preview-hotspots"/);
  assert.match(html, /class="fixed-doc-preview-hotspot"[\s\S]*'is-missing': !slot\.detected/);
  assert.doesNotMatch(html, /fixedDocPreviewQrHotspots|fixedDocPreviewShowQrHotspots/);
  assert.doesNotMatch(html, /fixedDocActiveQrSourceId|fixedDocQrSourceCatalog/);
  assert.match(html, /fixedDocPreviewFit/);
  assert.match(html, /@wheel\.prevent="onFixedDocPreviewWheel"/);
  assert.doesNotMatch(html, /class="fixed-doc-preview-region-draft"/);
  assert.match(html, /class="fixed-doc-footer"/);
  assert.match(html, /@click="closeFixedDocSettings">閉じる/);
  assert.match(html, /@click="goFixedDocPrevStep">前へ/);
  assert.match(html, /@click="goFixedDocNextStep">次へ/);
  assert.match(html, /@click="saveFixedDocSettings">保存/);
  assert.doesNotMatch(html, />Step1 テンプレートから解析</);
  assert.doesNotMatch(html, /OCR 字段清单/);
  assert.doesNotMatch(html, /字段赋值规则/);
  assert.doesNotMatch(html, /fixed-doc-preview-head/);
  assert.doesNotMatch(html, /fixed-doc-preview-meta/);
  assert.doesNotMatch(html, /fixed-doc-qr-source-caption/);
  assert.match(html, /@click="fixedDocReadTab = 'table'"/);
  const step1Html = html.slice(
    html.indexOf('<section v-show="fixedDocSetupStep === 1"'),
    html.indexOf('<section v-show="fixedDocSetupStep === 2"'),
  );
  assert.match(step1Html, /分類信頼度閾値/);
  assert.match(step1Html, /分類信頼度閾値[\s\S]*<span class="fixed-doc-required">必須<\/span>/);
  assert.match(step1Html, /案件集約時の画像分類信頼度/);
  assert.match(step1Html, /v-model="fixedDocClassificationConfidenceThreshold"/);
  assert.match(step1Html, /<el-input-number[\s\S]*controls-position="right"[\s\S]*class="fixed-doc-image-control fixed-doc-image-number"/);
  assert.match(step1Html, /class="fixed-doc-threshold-unit">%/);
  assert.match(main, /const fixedDocClassificationConfidenceThreshold = ref\(80\)/);
  assert.match(html, /<section v-show="fixedDocSetupStep === 4"[\s\S]*<el-input-number[\s\S]*controls-position="right"[\s\S]*class="fixed-doc-image-control fixed-doc-image-number"/);
  assert.match(main, /label: '分割判定閾値', kind: 'number', value: 80, min: 0, max: 100/);
  assert.doesNotMatch(main, /value: '80 %'/);
  assert.match(css, /\.fixed-doc-image-number\.el-input-number\s*\{[\s\S]*width:\s*150px;/);
  const step2TabsHtml = html.slice(
    html.indexOf('<section v-show="fixedDocSetupStep === 2"'),
    html.indexOf('<template v-if="fixedDocReadTab === \'text\'">'),
  );
  // QR 設定ビュー（OCR設定／QR設定 の切替と QR ソース目録の設定 UI）は撤去済み。
  // 値は「全 QR を連結 → 区切り文字で扁平分割 → 項目順に写像」で解決する。
  assert.match(step2TabsHtml, /class="fixed-doc-tabs-actions"[\s\S]*class="fixed-doc-ai-generate"/);
  assert.doesNotMatch(html, /fixed-doc-read-mode-switch/);
  assert.doesNotMatch(html, /class="fixed-doc-read-mode-bar"/);
  assert.doesNotMatch(css, /fixed-doc-read-mode-switch/);
  assert.doesNotMatch(main, /fixedDocReadMode/);
  assert.doesNotMatch(main, /fixedDocShowQrReadMode|fixedDocShowQrEffectPanel|fixedDocQrReadRows/);
  assert.doesNotMatch(main, /fixedDocHasQrMapping|fixedDocCanAddQrSource|fixedDocHasQrSourceCatalog/);
  assert.doesNotMatch(html, /class="fixed-doc-qr-workspace"/);
  assert.doesNotMatch(html, /class="fixed-doc-qr-source-(strip|scroll|actions|parse|add|panel)"/);
  assert.doesNotMatch(html, /:data-source-id="src\.id"/);
  assert.doesNotMatch(html, /v-if="fixedDocPreviewQrHotspots\.length"/);
  assert.doesNotMatch(html, /@click="onFixedDocQrMappingRowClick\(row, \$event\)"/);
  assert.doesNotMatch(html, /class="fixed-doc-qr-source-generate"/);
  assert.doesNotMatch(html, /fixedDocQrSourceStatusLabel/);
  assert.doesNotMatch(html, /fixed-doc-qr-source-enable/);
  assert.doesNotMatch(html, />再定位</);
  assert.doesNotMatch(html, /src\.enabled === false \? 'OFF' : 'ON'/);
  assert.doesNotMatch(html, />🗑</);
  // 連結読み取りモデル：連結 → 扁平分割 → 項目順写像
  assert.match(main, /const FIXED_DOC_QR_FIELD_NAMES = \[/);
  assert.match(main, /const FIXED_DOC_QR_DELIMITERS = \['\$', '\^'\];/);
  assert.match(main, /\.filter\(\(slot\) => slot\.payload\.includes\('\$'\)\)/);
  assert.match(main, /const fixedDocQrDataSegments = computed\(\(\) => fixedDocQrDetectedSegments\.value\.map/);
  assert.match(main, /const fixedDocQrConcatenatedPayload = computed\(\(\) => fixedDocQrDataSegments\.value\.join\(''\)\)/);
  assert.match(main, /const fixedDocQrValues = computed\(\(\) => \{[\s\S]*?payload\.split\(FIXED_DOC_QR_SPLIT_PATTERN\)/);
  assert.match(main, /const fixedDocQrFieldMappings = computed\(\(\) => FIXED_DOC_QR_FIELD_NAMES\.map/);
  assert.match(main, /function getFixedDocQrFieldPreviewValue\(fieldRule = \{\}\) \{[\s\S]*?fixedDocQrValueByName\.value\.get\(name\)/);
  assert.match(main, /let hasQrMapping = fixedDocQrValueByName\.value\.has\(fieldName\);/);
  // QR 読取結果バー：AI 入力欄の下・項目表の上に置き、ON/OFF スイッチと QR スキャンを持つ
  assert.match(html, /:model-value="fixedDocCommonPrompt"[\s\S]*?class="fixed-doc-qr-result"[\s\S]*?<div class="fixed-doc-table-panel">/);
  assert.match(html, /class="fixed-doc-qr-result"[\s\S]*'is-incomplete': fixedDocQrReadStatus\.enabled && !fixedDocQrReadStatus\.ok/);
  assert.match(html, /'is-disabled': !fixedDocQrReadStatus\.enabled/);
  assert.match(html, /class="fixed-doc-qr-result-switch"[\s\S]*:model-value="fixedDocQrReadEnabled"[\s\S]*@change="onFixedDocQrReadToggle"/);
  // スイッチを入れたらその場でスキャンを走らせる（枠を出さずに終わらせない）。
  assert.match(main, /function onFixedDocQrReadToggle\(enabled\) \{[\s\S]*?fixedDocQrReadEnabled\.value = true;[\s\S]*?runFixedDocQrScan\(\);/);
  // 門は帳票の項目定義数（= QR 仕様の値数）と比べる。デモの項目表は一部しか描いていない。
  assert.match(main, /const expectedValues = FIXED_DOC_QR_FIELD_NAMES\.length;/);
  assert.match(html, /<div v-if="fixedDocQrReadStatus\.enabled" class="fixed-doc-qr-result-slots">/);
  assert.match(html, /v-for="slot in fixedDocQrReadSlots"[\s\S]*class="fixed-doc-qr-result-slot"[\s\S]*'is-scanning': !slot\.scanned,[\s\S]*'is-missing': slot\.scanned && !slot\.detected/);
  // 読取には時間がかかる。枠は 1 つずつ確定させ、全部そろうまでパス徽标は出さない。
  assert.match(main, /const FIXED_DOC_QR_SCAN_STEP_MS = \d+;/);
  assert.match(main, /for \(const slot of slots\) \{[\s\S]*?await waitFixedDocQrScan\(FIXED_DOC_QR_SCAN_STEP_MS\);[\s\S]*?fixedDocQrScannedIds\.add\(slot\.id\);/);
  assert.match(html, /class="fixed-doc-qr-result-count is-scanning"[\s\S]*?>スキャン中…</);
  assert.match(main, /fixedDocQrReadSlots\.value\.filter\(\(slot\) => slot\.scanned\)/);
  // 6 つの QR 枠はスイッチのすぐ横（ヘッド内、同一行）に並べる。別行の枠行は作らない。
  assert.match(html, /class="fixed-doc-qr-result-switch"[\s\S]*<\/el-switch>[\s\S]*<div v-if="fixedDocQrReadStatus\.enabled" class="fixed-doc-qr-result-slots">/);
  // 枠のラベルは QR id だけ（QR1 / QR2 …）。項目範囲や説明文は出さない。
  assert.match(html, /:data-source-id="slot\.id"[\s\S]*?>\{\{ slot\.id \}\}<\/div>/);
  // 「QR 読取」の横に情報アイコン（tooltip）。LIAJ 診断書テンプレート専用の説明。
  assert.match(html, /class="fixed-doc-qr-result-title">QR 読取<\/span>[\s\S]*?class="fixed-doc-info" tabindex="0">i<\/span>/);
  assert.match(html, /LIAJ診断書テンプレート専用/);
  // 顧客に見せるバッジは「QR 優先パス適用中」だけ。値数が合わない時の赤バッジは
  // 原因を言い切れない（スキャン側か項目数側か）ので出さない。理由は下の提示行で伝える。
  assert.match(html, /class="fixed-doc-qr-result-path is-qr"[\s\S]*?>QR 読取優先パス適用中</);
  assert.doesNotMatch(html, /fixed-doc-qr-result-path is-ocr/);
  assert.doesNotMatch(html, /QR 不足 — OCR で読取/);
  assert.doesNotMatch(css, /\.fixed-doc-qr-result-path\.is-ocr/);
  assert.doesNotMatch(html, /fixed-doc-qr-result-(label|range|id)"/);
  assert.doesNotMatch(html, /\{\{ fixedDocQrReadStatus\.detected \}\}/);
  assert.doesNotMatch(html, /値 \{\{ fixedDocQrReadStatus\.valueCount \}\}/);
  assert.match(html, /v-if="!fixedDocQrReadStatus\.enabled" class="fixed-doc-qr-result-count">無効 — OCR のみで読取<\/span>/);
  // QR スキャンは残す（QR を読む運用では必須）
  assert.match(html, /class="fixed-doc-qr-scan-btn"[\s\S]*?:disabled="!fixedDocQrReadStatus\.enabled"[\s\S]*?:loading="fixedDocQrScanActive"[\s\S]*?@click="runFixedDocQrScan"[\s\S]*?>QR スキャン<\/el-button>/);
  // 顧客向け文言。技術的な数値（値数/項目数）は出さない。
  // 値数が合わない原因はスキャン側だけではない（項目数を変えた場合もある）ので、原因別に出し分ける。
  assert.match(html, /fixedDocQrReadStatus\.slotsMissing[\s\S]*?>QR の読み取りが不完全です。画像を再アップロードして再スキャンしてください。</);
  assert.match(html, /QR から読み取った値の数が項目数と一致しません。項目の設定を確認してください。/);
  assert.match(main, /slotsMissing: enabled && detected < expected,/);
  assert.doesNotMatch(html, /項目位置がずれています/);
  assert.doesNotMatch(html, /class="fixed-doc-qr-result-(add|remove|parse|actions)"/);
  // QR 連結読取 は既定 OFF。admin が明示的に ON にした帳票だけ QR 優先パスになる。
  assert.match(main, /const fixedDocQrReadEnabled = ref\(false\);/);
  assert.match(main, /const fixedDocQrExpectedSlots = computed\(\(\) => Object\.keys\(FIXED_DOC_QR_SOURCE_RECTS\)/);
  assert.match(main, /const fixedDocQrUndetectedIds = reactive\(new Set\(\)\);/);
  assert.match(main, /const fixedDocQrDetectedSegments = computed\(\(\) => \{[\s\S]*?if \(!fixedDocQrReadEnabled\.value\) return \[\];/);
  assert.match(main, /const fixedDocQrReadSlots = computed\(\(\) => fixedDocQrExpectedSlots\.value\.map/);
  assert.match(main, /const fixedDocQrReadStatus = computed\(\(\) => \{[\s\S]*?const complete = valueCount === expectedValues;[\s\S]*?ok: !enabled \|\| complete/);
  assert.match(main, /const fixedDocPreviewQrSlots = computed\(\(\) => \{[\s\S]*?fixedDocQrReadSlots\.value/);
  assert.match(main, /async function runFixedDocQrScan\(options = \{\}\) \{[\s\S]*?\.includes\('\$'\)[\s\S]*?fixedDocQrUndetectedIds\.clear\(\);[\s\S]*?fixedDocQrUndetectedIds\.add\(id\)/);
  assert.match(main, /runFixedDocQrScan,/);
  // QR 設定ビューの代わりに Step2 への遷移で自動スキャンする（ビューは作らない）
  assert.match(main, /watch\(fixedDocSetupStep, \(step\) => \{[\s\S]*?if \(step === 2 && fixedDocQrReadEnabled\.value\) runFixedDocQrScan\(\{ silent: true \}\);/);
  assert.match(css, /\.fixed-doc-qr-result\.is-disabled\s*\{/);
  assert.match(css, /\.fixed-doc-qr-result-switch\s*\{[\s\S]*?flex:\s*none;/);
  assert.match(css, /\.fixed-doc-qr-result-count\s*\{[\s\S]*?margin-left:\s*auto;/);
  assert.match(css, /\.fixed-doc-qr-scan-btn\s*\{[\s\S]*?flex:\s*none;/);
  assert.match(css, /\.fixed-doc-qr-result-slot\.is-missing\s*\{[\s\S]*border-style:\s*dashed;/);
  assert.match(css, /\.fixed-doc-preview-hotspot\.is-missing\s*\{[\s\S]*border-color:\s*#e31b54;/);
  assert.match(main, /function parseFixedDocQrSourcesFromTemplate\(\)/);
  assert.match(main, /function runFixedDocQrSourcesScan/);
  assert.match(main, /function focusFixedDocQrSource\(sourceId\)/);
  assert.match(main, /fixedDocActiveQrSourceId\.value[\s\S]*fixedDocQrSourceCatalog\.find/);
  assert.match(main, /fixedDocHasConfiguredFieldQrMapping\.value[\s\S]*ElMessageBox\.confirm/);
  assert.match(main, /function clearAllFixedDocConfiguredQrFieldMappings/);
  assert.match(main, /function updateFixedDocQrSourceMappingRefs\(idMap, removedSourceId\)/);
  assert.match(main, /if \(!rule \|\| !rule\.qrSourceId\) return;/);
  assert.match(main, /else if \(removedSourceId && rule\.qrSourceId === removedSourceId\)/);
  assert.match(main, /fixedDocQrSuppressAutoSourceAssignment/);
  assert.match(main, /runFixedDocQrSourcesScan\(\{ clearFieldMappings: true \}\)/);
  assert.match(html, /class="fixed-doc-ai-generate"[\s\S]*@click="runFixedDocAiGenerate"[\s\S]*>AI自動生成/);
  assert.match(html, /<el-dropdown trigger="click" placement="bottom-end" popper-class="fixed-doc-action-dropdown" @command="handleFixedDocTemplateAction">[\s\S]*テンプレートをダウンロード[\s\S]*一括ダウンロード[\s\S]*一括インポート[\s\S]*<\/el-dropdown>/);
  assert.match(html, /<el-dropdown trigger="click" placement="bottom-end" popper-class="fixed-doc-action-dropdown" @command="handleFixedDocSettingsAction">[\s\S]*エクスポート設定[\s\S]*読取モデル設定[\s\S]*<\/el-dropdown>/);
  assert.match(main, /function handleFixedDocTemplateAction\(command\) \{[\s\S]*command === 'download-template'[\s\S]*exportFixedDocFieldTemplate\(\);/);
  assert.match(main, /function handleFixedDocSettingsAction\(command\) \{[\s\S]*command === 'read-model-settings'[\s\S]*openReadModelSettings\(\);/);
  assert.match(css, /\.fixed-doc-action-dropdown \.el-dropdown-menu\s*\{[\s\S]*min-width:\s*164px;/);
  assert.doesNotMatch(html, /class="fixed-doc-qr-source-generate"/);
  assert.doesNotMatch(html, /fixedDocQrSourceStatusLabel/);
  assert.doesNotMatch(html, /fixed-doc-qr-source-enable/);
  assert.doesNotMatch(html, />再定位</);
  assert.doesNotMatch(html, /src\.enabled === false \? 'OFF' : 'ON'/);
  assert.doesNotMatch(html, />🗑</);
  // QR 読取テーブル（項目タイプ／取値方法／順序 の列）も撤去済み
  assert.doesNotMatch(html, /fixed-doc-read-body--qr/);
  assert.doesNotMatch(html, /fixed-doc-table--qr-read/);
  assert.doesNotMatch(html, /fixed-doc-qr-type-col|fixed-doc-qr-no-col|fixed-doc-qr-extract-col|fixed-doc-qr-index-col/);
  assert.doesNotMatch(html, /fixed-doc-qr-split-switch/);
  assert.doesNotMatch(html, /fixed-doc-type-readonly/);
  assert.doesNotMatch(html, /getFixedDocQrFetchIndexInput\(row\)/);
  assert.doesNotMatch(html, /getFixedDocQrDelimiterInput\(row\)/);
  assert.doesNotMatch(html, /setFixedDocQrSplitEnabled\(row\.fieldId/);
  assert.doesNotMatch(html, /fixed-doc-qr-source-select/);
  assert.doesNotMatch(html, /<th class="fixed-doc-qr-extract-col">抽出方式<\/th>/);
  assert.match(css, /\.el-switch\s*\{[\s\S]*--el-switch-on-color:\s*#667085;[\s\S]*--el-switch-off-color:\s*#d0d5dd;/);
  assert.match(css, /\.el-switch \.el-switch__action\s*\{[\s\S]*background-color:\s*#fff;/);
  assert.doesNotMatch(css, /fixed-doc-table--qr-read/);
  assert.doesNotMatch(css, /fixed-doc-qr-type-col|fixed-doc-qr-no-col|fixed-doc-qr-index-cell|fixed-doc-qr-split-switch/);
  assert.doesNotMatch(css, /fixed-doc-type-readonly/);
  assert.doesNotMatch(css, /\.fixed-doc-qr-fetch-index/);
  assert.doesNotMatch(main, /const FIXED_DOC_QR_EXTRACT_PLAIN = '普通OCR';/);
  assert.match(main, /const FIXED_DOC_QR_EXTRACT_PLAIN = '全文';/);
  assert.match(main, /const FIXED_DOC_QR_EXTRACT_SPLIT = '分割';/);
  assert.match(main, /function setFixedDocQrSplitEnabled\(fieldRef, enabled\) \{[\s\S]*?qrExtractMethod: enabled \? FIXED_DOC_QR_EXTRACT_SPLIT : FIXED_DOC_QR_EXTRACT_PLAIN/);
  assert.doesNotMatch(html, /<th>操作・処理<\/th>/);
  assert.match(html, /<th class="fixed-doc-row-actions-col">操作<\/th>/);
  assert.match(html, /class="fixed-doc-row-actions"/);
  assert.match(html, /class="fixed-doc-row-drag-handle"/);
  assert.match(html, /class="fixed-doc-row-delete"/);
  assert.match(html, /@click="deleteFixedDocTextField\(row\.fieldId\)"/);
  assert.doesNotMatch(html, /class="fixed-doc-row-move"/);
  assert.doesNotMatch(html, /@click="moveFixedDocTextField\(row\.fieldId, 'up'\)"/);
  assert.doesNotMatch(html, /@click="moveFixedDocTextField\(row\.fieldId, 'down'\)"/);
  assert.doesNotMatch(html, /:disabled="!row\.canMoveUp"/);
  assert.doesNotMatch(html, /:disabled="!row\.canMoveDown"/);
  assert.doesNotMatch(html, /canMoveFixedDocTextField/);
  assert.match(html, /@dragstart="onFixedDocTextFieldDragStart\(row\.fieldId, \$event\)"/);
  assert.match(html, /@dragover\.prevent="onFixedDocTextFieldDragOver\(row\.fieldId, \$event\)"/);
  assert.match(html, /@drop\.prevent="onFixedDocTextFieldDrop\(row\.fieldId, \$event\)"/);
  assert.match(html, /fixedDocTextFieldDropTargetId === row\.fieldId/);
  assert.match(main, /const fixedDocFieldOrder = ref\(\[\]\);/);
  assert.match(main, /const fixedDocDeletedFieldNames = reactive\(new Set\(\)\);/);
  assert.match(main, /function deleteFixedDocTextField\(fieldRef\)/);
  assert.match(main, /function reorderFixedDocTextField\(dragFieldId, targetFieldId\)/);
  assert.match(main, /function moveFixedDocTextField\(fieldRef, direction\)/);
  assert.doesNotMatch(main, /function canMoveFixedDocTextField/);
  assert.match(main, /canMoveUp: idx > 0,/);
  assert.match(main, /canMoveDown: idx < fieldNames\.length - 1,/);
  assert.match(main, /const fixedDocTextFieldDropTargetId = ref\(''\);/);
  assert.match(main, /function onFixedDocTextFieldDragOver\(fieldId, event\) \{[\s\S]*?fixedDocTextFieldDropTargetId\.value = fieldId;[\s\S]*?\}/);
  const dragOverBody = main.slice(
    main.indexOf('function onFixedDocTextFieldDragOver(fieldId, event)'),
    main.indexOf('function onFixedDocTextFieldDrop(fieldId, event)'),
  );
  assert.doesNotMatch(dragOverBody, /reorderFixedDocTextField/);
  assert.match(main, /function onFixedDocTextFieldDrop\(fieldId, event\) \{[\s\S]*?reorderFixedDocTextField\(dragFieldId, fieldId\);[\s\S]*?\}/);
  assert.match(css, /\.fixed-doc-table tr\.is-field-drop-target td\s*\{[^}]*background:\s*#eff8ff;/);
  assert.doesNotMatch(css, /\.fixed-doc-row-move/);
  assert.match(css, /\.fixed-doc-row-delete:focus-visible,[\s\S]*?box-shadow:\s*0 0 0 2px #b2ddff;/);
  assert.match(css, /\.fixed-doc-table th\.fixed-doc-row-actions-col,[\s\S]*?width:\s*80px;/);
  // QR 読取テーブルの タイプ 列（読み取り専用）は撤去済み。OCR 設定側のタイプ選択は残る。
  assert.doesNotMatch(html, /class="fixed-doc-qr-type-select"/);
  assert.doesNotMatch(html, /fixed-doc-qr-type-col/);
  assert.match(main, /const fixedDocFieldTypes = reactive\(\{\}\);/);
  assert.match(main, /function setFixedDocFieldType\(fieldRef, type\)/);
  assert.match(main, /function normalizeFixedDocFieldType\(type\)/);
  assert.match(html, /タイプ[\s\S]*string：文字列、number：数値/);
  assert.doesNotMatch(html, /content="string：文字列、number：数値、enum：候補値"/);
  assert.match(html, /setFixedDocTableColumnType\(table\.id, col\.columnId, \$event\)/);
  assert.doesNotMatch(html, /getFixedDocQrDelimiterInput\(row\)/);
  assert.doesNotMatch(html, /commitFixedDocQrDelimiterDraft\(row\.fieldId\)/);
  assert.doesNotMatch(html, /fixed-doc-qr-delim-select"[\s\S]*placeholder="\$"/);
  assert.doesNotMatch(html, /v-if="shouldShowFixedDocQrFieldDelimiter\(row\)"[\s\S]*<el-select/);
  assert.doesNotMatch(html, /v-if="row\.qrSourceId"[\s\S]*class="fixed-doc-qr-source-select"/);
  assert.doesNotMatch(html, /:model-value="row\.qrSourceId"/);
  assert.doesNotMatch(main, /const fixedDocQrReadRows = computed/);
  assert.doesNotMatch(
    main.slice(main.indexOf('function ensureFixedDocFieldRules'), main.indexOf('function setFixedDocFieldRule')),
    /ensureFixedDocQrSourceAssignments/,
  );
  assert.doesNotMatch(html, /未設定（OCR）/);
  assert.doesNotMatch(html, /正解サンプル[\s\S]{0,200}QR読取/);
  assert.match(html, /正解サンプル[\s\S]*content="この項目は自動ルールマッチングと読取に使用されます。"/);
  assert.match(html, /正解サンプル[\s\S]*content="この列は自動ルールマッチングと読取に使用されます。"/);
  assert.match(html, /setFixedDocFieldRule\(row\.fieldId,/);
  assert.match(html, /class="fixed-doc-table-config-panel"/);
  assert.match(html, /テーブル抽出条件/);
  assert.match(html, /class="fixed-doc-table-config-name"/);
  assert.match(html, /必須項目[\s\S]*content="項目の読み取り結果が空の場合は、確認画面で赤く表示されます。"/);
  assert.match(html, /必須[\s\S]*content="列の読み取り結果が空の場合は、確認画面で赤く表示されます。"/);
  assert.match(html, /マスク[\s\S]*content="この項目に個人情報脱敏（マスキング）を適用するかどうかを指定します。"/);
  // マスクはテキスト読取の項目単位設定。テーブル情報読取 の列定義にはマスク列を置かない
  assert.doesNotMatch(html, /この列に個人情報脱敏（マスキング）を適用するかどうかを指定します。/);
  assert.doesNotMatch(html, /マスク[\s\S]{0,200}v-model="col\.mask"/);
  assert.match(html, /<td><el-switch :model-value="row\.required" size="small"><\/el-switch><\/td>/);
  assert.doesNotMatch(html, /class="fixed-doc-table-qr-panel"/);
  assert.doesNotMatch(html, /class="fixed-doc-table-qr-read"/);
  assert.doesNotMatch(html, /setFixedDocTableColumnRule\(table\.id, col\.columnId, \{ qrSourceId/);
  assert.doesNotMatch(html, /<strong>テーブル QR 読取<\/strong>/);
  assert.doesNotMatch(html, /fixed-doc-qr-toggle-col/);
  assert.doesNotMatch(html, />解析样例</);
  assert.doesNotMatch(html, /fixed-doc-qr-parsed-sample/);
  assert.doesNotMatch(html, /fixed-doc-test-source-label/);
  assert.doesNotMatch(html, /読取元：/);
  assert.match(html, /class="fixed-doc-test-card-head"[\s\S]*?<span v-if="row\.sourceLabel" class="fixed-doc-test-source-tag">\{\{ row\.sourceLabel \}\}<\/span>/);
  const step5TestHtml = html.slice(html.indexOf('class="fixed-doc-panel fixed-doc-test-panel"'), html.indexOf('class="fixed-doc-test-table-list"'));
  assert.doesNotMatch(step5TestHtml, /row\.confidence/);
  assert.doesNotMatch(step5TestHtml, /row\.rangeLabel/);
  assert.doesNotMatch(step5TestHtml, /row\.maskLabel/);
  assert.doesNotMatch(html, /class="fixed-doc-test-summary"/);
  assert.match(html, /fixed-doc-test-error">\{\{ row\.errorMessage \}\}/);
  assert.match(main, /const FIXED_DOC_TEST_READ_SCENARIOS =/);
  assert.match(main, /function resolveFixedDocTestReadContext\(/);
  assert.match(main, /path: 'fallback', confidence: '62\.0 %'/);
  assert.match(main, /const FIXED_DOC_TEST_OCR_REVIEW_MESSAGE = '信頼度が閾値未満'/);
  assert.match(main, /function getFixedDocTestReviewReasonLabel\(/);
  assert.match(main, /reviewReasonLabel: getFixedDocTestReviewReasonLabel\(review\.reason\)/);
  assert.match(main, /const FIXED_DOC_TABLE_TEST_COLUMNS/);
  assert.match(main, /function getFixedDocTableTestVisibleColumns\(table\)/);
  assert.match(html, /class="fixed-doc-test-error-rule">\{\{ row\.reviewReasonLabel \}\}/);
  assert.match(main, /failureRule === '要確認（HITL）'/);
  assert.doesNotMatch(html, /row\.rangeConclusion|row\.rangeFail/);
  assert.doesNotMatch(main, /rangeConclusion|buildFixedDocTestRangeConclusion|rangeFail/);
  assert.match(main, /hitlRules\.includes\('normal_range_exceeded'\)/);
  assert.match(main, /hitlRules\.includes\('low_confidence_and_range_exceeded'\)/);
  // Step5 的测试对象与 Step2/Step3 相同（同一字段集合，Step2 中被マスク的字段除外）
  // 卡片番号沿用字段行番号（fixedDocTextRows 的 row.no），并按其行序展示
  assert.doesNotMatch(main, /FIXED_DOC_TEST_FIELD_NAMES/);
  assert.match(main, /fixedDocTextRows\.value\s*\n\s*\.filter\(\(row\) => !row\.mask\)/);
  assert.match(main, /no: row\.no,/);
  assert.match(main, /const fixedDocTableTestRows = computed\(/);
  assert.match(main, /hitlRules\.includes\('low_confidence'\)/);
  assert.match(main, /function getFixedDocFieldId\(fieldName, index = -1\)/);
  assert.match(main, /function renameFixedDocQrSource\(sourceId, label\)/);
  assert.match(main, /const fixedDocQrSourceCatalog = reactive\(\[\]\);/);
  assert.match(main, /function listFixedDocQrTemplateDetections\(\)/);
  assert.match(main, /function getFixedDocQrExcludedSourceKeys\(\)/);
  assert.doesNotMatch(main, /FIXED_DOC_QR_SOURCE_LIMIT/);
  assert.doesNotMatch(main, /const fixedDocCanAddQrSource = computed/);
  assert.match(main, /function addFixedDocQrSourceFromIgnored/);
  assert.match(main, /function removeFixedDocQrSource\(sourceId\)/);
  assert.match(main, /removeFixedDocQrSource\(sourceId\)[\s\S]*?reindexFixedDocQrSources\(sourceId\)/);
  assert.match(main, /removed\.sourceKey \|\| removed\.id/);
  assert.match(main, /const fixedDocQrNumberOptions = computed\(\(\) => fixedDocQrSourceCatalog\.map\(\(slot\) => \(\{\s*value: slot\.id,\s*label: slot\.id,/);
  assert.doesNotMatch(main, /label: `\$\{slot\.id\}\$\{slot\.label/);
  assert.match(main, /Math\.max\(0, \.\.\.fixedDocQrSourceCatalog\.map/);
  assert.doesNotMatch(main, /let index = fixedDocQrSourceCatalog\.length \+ 1;/);
  assert.match(main, /const sourceId = options\.sourceId \|\| getNextFixedDocQrSourceId\(\);/);
  assert.doesNotMatch(main, /const sourceId = options\.sourceId \|\| detection\.sourceId \|\| getNextFixedDocQrSourceId\(\);/);
  assert.match(main, /function normalizeFixedDocQrRegionRect\(rect\)/);
  assert.match(main, /function assignFixedDocQrRegionRect\(sourceId, rect\)/);
  assert.doesNotMatch(main, /const fixedDocQrRegionDraft = reactive/);
  assert.match(main, /function reindexFixedDocQrSources\(removedSourceId = ''\)/);
  assert.match(main, /updateFixedDocQrSourceMappingRefs\(idMap, removedSourceId\)/);
  assert.match(main, /sourceKey: detection\.sourceKey/);
  assert.match(main, /source\?\.sourceKey \|\| sourceId/);
  assert.match(main, /function runFixedDocQrSourcesScan/);
  assert.match(main, /function rescanFixedDocQrSourcesFromTemplate/);
  assert.match(main, /function normalizeFixedDocFieldType\(type\)/);
  assert.match(main, /return \['string', 'number', 'enum'\]\.includes\(type\)/);
  assert.match(main, /function inferFixedDocFieldTypeFromName\(fieldName = ''\)/);
  assert.match(main, /function normalizeFixedDocNormalConditionForRule\(target = \{\}, rule = ''\)/);
  assert.match(main, /function canFixedDocRuleHaveNormalCondition\(rule = ''\)/);
  assert.match(main, /return normalized !== 'マスタ照合' && normalized !== 'テキスト置換'/);
  assert.doesNotMatch(main, /const FIXED_DOC_NORMAL_CONDITION_EXCLUDED_RULES = new Set\(/);
  assert.match(main, /const FIXED_DOC_NUMBER_RANGE_RULES = new Set\(\[/);
  assert.doesNotMatch(main, /const FIXED_DOC_RANGE_CAPABLE_RULES = new Set\(\[/);
  assert.match(html, /@click="runFixedDocAiMatching"/);
  assert.doesNotMatch(html, /title="AIマッチング — 処理ルールと判定条件"/);
  assert.doesNotMatch(html, /v-model="fixedDocAiMatchingDialogVisible"/);
  assert.doesNotMatch(main, /fixedDocAiMatchingDialogVisible/);
  assert.doesNotMatch(main, /fixedDocAiMatchingDraft/);
  assert.doesNotMatch(main, /confirmFixedDocAiMatching/);
  assert.match(main, /function runFixedDocAiMatching\(\)/);
  assert.doesNotMatch(main, /function inferFixedDocAiMatchingRange\(/);
  assert.match(main, /function buildFixedDocAiMatchingDraft\(\)[\s\S]*?rule,[\s\S]*?\}\);/);
  assert.doesNotMatch(main, /function buildFixedDocAiMatchingDraft\(\)[\s\S]*?rangeSummary/);
  assert.match(html, /<th class="fixed-doc-rule-col">処理ルール<\/th>/);
  assert.match(html, /<th v-if="fixedDocShowNormalConditionColumn" class="fixed-doc-normal-condition-col">[\s\S]*?正常条件[\s\S]*?<\/th>/);
  assert.doesNotMatch(html, /<th class="fixed-doc-rule-detail-col">設定内容<\/th>/);
  assert.doesNotMatch(html, /<th class="fixed-doc-master-col">マスタ<\/th>/);
  assert.doesNotMatch(html, /<th class="fixed-doc-priority-col">優先度<\/th>/);
  const step3TextRulesHtml = html.slice(
    html.indexOf('<div v-if="fixedDocRuleTab === \'text\'"'),
    html.indexOf('<div v-if="fixedDocRuleTab === \'table\'"'),
  );
  assert.doesNotMatch(step3TextRulesHtml, /<th class="fixed-doc-range-col">正常範囲<\/th>/);
  assert.match(step3TextRulesHtml, /:class="\{ 'fixed-doc-table--rules-wide': !fixedDocShowNormalConditionColumn \}"/);
  const firstRuleCellHtml = step3TextRulesHtml.match(/<td class="fixed-doc-rule-col">([\s\S]*?)<\/td>/)?.[1] || '';
  assert.match(firstRuleCellHtml, /fixed-doc-rule-cell/);
  assert.match(step3TextRulesHtml, /<td class="fixed-doc-rule-col">/);
  assert.doesNotMatch(step3TextRulesHtml, /<td class="fixed-doc-rule-detail-col">/);
  assert.match(step3TextRulesHtml, /<td v-if="fixedDocShowNormalConditionColumn" class="fixed-doc-normal-condition-col">/);
  assert.match(step3TextRulesHtml, /v-if="isFixedDocMasterRule\(row\)" class="fixed-doc-rule-detail fixed-doc-rule-detail--master"/);
  assert.match(step3TextRulesHtml, /fixed-doc-rule-master-select/);
  assert.match(step3TextRulesHtml, /fixed-doc-rule-master-priority/);
  assert.match(step3TextRulesHtml, /v-else-if="isFixedDocTextReplaceRule\(row\)" class="fixed-doc-rule-detail fixed-doc-rule-detail--replace"/);
  assert.match(css, /\.fixed-doc-rule-cell \{\s*display: flex;\s*flex-direction: column;\s*flex-wrap: nowrap;\s*align-items: flex-start;/);
  assert.match(css, /\.fixed-doc-rule-cell > \.fixed-doc-rule-select \{\s*flex: none;\s*width: 220px;/);
  assert.match(css, /\.fixed-doc-table--rules td \.fixed-doc-rule-cell > \.fixed-doc-rule-select\.el-select,[\s\S]*?width: 220px !important;/);
  assert.match(css, /\.fixed-doc-rule-cell > \.fixed-doc-rule-detail \{\s*flex: none;\s*width: 220px;/);
  assert.match(css, /\.fixed-doc-table--rules td \.fixed-doc-rule-cell \.el-select__wrapper,[\s\S]*?\.fixed-doc-table--table-rules td \.fixed-doc-rule-cell \.el-input__wrapper \{[\s\S]*?height: 28px;/);
  assert.match(css, /\.fixed-doc-rule-master-select \{\s*flex: 0 0 166px;\s*width: 166px;/);
  assert.match(css, /\.fixed-doc-table--rules td \.fixed-doc-rule-detail--master \.fixed-doc-rule-master-select\.el-select \{[\s\S]*?width: 166px !important;/);
  assert.match(css, /\.fixed-doc-table--rules th\.fixed-doc-rule-col,[\s\S]*?width: 240px;/);
  assert.match(css, /\.fixed-doc-table--rules th\.fixed-doc-normal-condition-col,[\s\S]*?width: 280px;/);
  assert.match(css, /\.fixed-doc-normal-condition-col \.fixed-doc-rule-detail--range \{[\s\S]*?flex-wrap: nowrap;/);
  assert.match(css, /\.fixed-doc-normal-condition-col \.fixed-doc-rule-detail--range \.fixed-doc-range-input \{[\s\S]*?flex: 1 1 72px;/);
  assert.match(css, /\.fixed-doc-range-mode-select \.el-select__wrapper\s*\{[\s\S]*?min-height:\s*34px;[\s\S]*?height:\s*34px;/);
  assert.match(css, /\.fixed-doc-normal-condition-col \.fixed-doc-range-mode-select \.el-select__wrapper\s*\{[\s\S]*?min-height:\s*34px;[\s\S]*?height:\s*34px;/);
  assert.match(css, /\.fixed-doc-rule-detail--range \.fixed-doc-range-input \.el-input__wrapper\s*\{[\s\S]*?min-height:\s*34px;[\s\S]*?height:\s*34px;/);
  assert.match(css, /\.fixed-doc-table--rules\.fixed-doc-table--rules-wide th\.fixed-doc-rule-col,/);
  assert.match(css, /\.fixed-doc-rule-detail--master \{\s*flex-wrap: nowrap;\s*min-width: 0;/);
  assert.match(css, /\.fixed-doc-rule-detail--replace \{\s*flex-wrap: nowrap;/);
  assert.match(css, /\.fixed-doc-table--rules td \.fixed-doc-rule-detail--replace \{[\s\S]*?width: 220px;/);
  assert.match(step3TextRulesHtml, /class="fixed-doc-rule-detail fixed-doc-rule-detail--range"/);
  assert.match(step3TextRulesHtml, /正常条件/);
  assert.match(step3TextRulesHtml, /v-if="canFixedDocRowHaveNormalCondition\(row\)"[\s\S]*?class="fixed-doc-rule-detail fixed-doc-rule-detail--range"/);
  assert.doesNotMatch(step3TextRulesHtml, /:disabled="!canFixedDocRowHaveNormalCondition\(row\)"/);
  assert.match(step3TextRulesHtml, /:model-value="getFixedDocNormalConditionMode\(row\)"/);
  assert.match(step3TextRulesHtml, /@change="setFixedDocNormalConditionMode\(row\.fieldId, \$event\)"/);
  assert.doesNotMatch(step3TextRulesHtml, /@update:model-value="setFixedDocFieldRule\(row\.fieldId, \{ rangeEnabled: \$event \}\)"/);
  assert.doesNotMatch(step3TextRulesHtml, />OFF<\/span>/);
  assert.match(step3TextRulesHtml, /getFixedDocNormalConditionModeOptions\(row\)/);
  assert.match(main, /function hasFixedDocRuleParams\(row\)/);
  assert.match(main, /function canFixedDocRuleHaveNormalCondition\(rule = ''\)/);
  assert.match(main, /function canFixedDocFieldHaveNormalCondition\(\)/);
  assert.match(main, /function canFixedDocRowHaveNormalCondition\(row\)/);
  assert.match(main, /function canFixedDocTableColumnHaveNormalCondition\(col\)/);
  assert.match(main, /function canFixedDocRowHaveNormalCondition\(row\) \{\s*return canFixedDocRuleHaveNormalCondition\(row\?\.rule\);/);
  assert.match(main, /function canFixedDocTableColumnHaveNormalCondition\(col\) \{\s*return canFixedDocRuleHaveNormalCondition\(col\?\.rule\);/);
  assert.match(main, /const fixedDocShowNormalConditionColumn = computed\(\(\) => \([\s\S]*?canFixedDocRowHaveNormalCondition\(row\)/);
  assert.match(main, /function shouldShowFixedDocTableNormalConditionColumn\(table\)/);
  assert.match(main, /function getFixedDocNormalConditionMode\(row\)/);
  assert.match(main, /function getFixedDocTableColumnNormalConditionMode\(col\)/);
  assert.match(main, /function getFixedDocNormalConditionModeOptions\(row\)/);
  assert.match(main, /function getFixedDocTableColumnNormalConditionModeOptions\(col\)/);
  assert.match(main, /function getFixedDocRangeModeOptionsByRule\(rule = ''\)/);
  assert.match(main, /return fixedDocRangeModeOptions;/);
  assert.match(main, /function getFixedDocRangeInputPlaceholder\(fieldType\)/);
  assert.match(main, /function parseFixedDocNormalEnumValues/);
  assert.match(main, /splitMultiValueDelimitedList/);
  assert.match(html, /カンマ区切りで入力/);
  assert.match(html, /getFixedDocRangeInputPlaceholder\(row\.type\)/);
  assert.match(html, /getFixedDocNormalValuesPlaceholder\(\)/);
  assert.match(main, /function getDefaultFixedDocNormalConditionModeByRule\(\)/);
  assert.match(main, /function setFixedDocNormalConditionMode\(fieldRef, mode\)/);
  assert.match(html, /<el-option label="enum" value="enum"><\/el-option>/);
  assert.match(main, /function setFixedDocTableColumnNormalConditionMode\(tableId, columnRef, mode\)/);
  assert.match(main, /const fixedDocRangeModeOptions = \[/);
  assert.match(main, /value: 'lt', label: '<'/);
  assert.match(main, /value: 'lte', label: '≤'/);
  assert.match(main, /value: 'gt', label: '>'/);
  assert.match(main, /value: 'gte', label: '≥'/);
  assert.doesNotMatch(main, /label: '不要'/);
  assert.doesNotMatch(main, /label: '不適用'/);
  assert.match(main, /value: 'enum', label: '列挙'/);
  assert.doesNotMatch(html, /<th class="fixed-doc-range-col">判定条件<\/th>/);
  assert.doesNotMatch(html, /class="fixed-doc-range-unit"/);
  assert.doesNotMatch(html, /placeholder="基準単位"/);
  assert.match(html, /content="処理ルール後の値の正常範囲を判定。"/);
  assert.match(html, /class="fixed-doc-range-mode-select"[\s\S]*?clearable/);
  assert.doesNotMatch(html, /class="fixed-doc-rule-unit-help"/);
  assert.doesNotMatch(html, /fixed-doc-normal-condition-row/);
  assert.match(html, /class="fixed-doc-normal-values-input"/);
  assert.match(main, /rangeMode/);
  assert.match(main, /normalValues/);
  assert.doesNotMatch(main, /rangeUnit/);
  assert.doesNotMatch(main, /function inferFixedDocAiMatchingRangeUnit\(fieldName, rule\)/);
  assert.doesNotMatch(html, /getFixedDocRangeKind\(row\.rule\) === 'date'[\s\S]*>当日<\/el-checkbox>/);
  assert.doesNotMatch(main, /function runFixedDocQrAiGenerate\(\)/);
  assert.doesNotMatch(main, /const exportValue = masked \? maskFixedDocPreviewValue/);
  assert.doesNotMatch(main, /readSourceKind/);
  assert.match(main, /value: processedValue,/);
  const step3TableRulesHtml = html.slice(
    html.indexOf('<div v-if="fixedDocRuleTab === \'table\'"'),
    html.indexOf('<section v-show="fixedDocSetupStep === 4"'),
  );
  assert.match(step3TableRulesHtml, /:class="\{ 'fixed-doc-table--rules-wide': !shouldShowFixedDocTableNormalConditionColumn\(table\) \}"/);
  assert.match(step3TableRulesHtml, /<th v-if="shouldShowFixedDocTableNormalConditionColumn\(table\)" class="fixed-doc-normal-condition-col">[\s\S]*?正常条件[\s\S]*?<\/th>/);
  assert.match(step3TableRulesHtml, /<td v-if="shouldShowFixedDocTableNormalConditionColumn\(table\)" class="fixed-doc-normal-condition-col">/);
  assert.match(step3TableRulesHtml, /v-if="canFixedDocTableColumnHaveNormalCondition\(col\)"[\s\S]*?class="fixed-doc-rule-detail fixed-doc-rule-detail--range"/);
  assert.match(step3TableRulesHtml, /:model-value="getFixedDocTableColumnNormalConditionMode\(col\)"/);
  assert.match(step3TableRulesHtml, /@change="setFixedDocTableColumnNormalConditionMode\(table\.id, col\.columnId, \$event\)"/);
  assert.match(step3TableRulesHtml, /getFixedDocTableColumnNormalConditionModeOptions\(col\)/);
  assert.doesNotMatch(step3TableRulesHtml, /<th class="fixed-doc-range-col">正常範囲<\/th>/);
  assert.doesNotMatch(step3TableRulesHtml, /@update:model-value="setFixedDocTableColumnRule\(table\.id, col\.columnId, \{ rangeEnabled: \$event \}\)"/);
  assert.match(main, /function validateFixedDocQrFetchIndex/);
  assert.match(main, /順序が重複しています/);
  assert.match(main, /最大値を超えています/);
  assert.match(main, /順序が連番ではありません/);
  assert.match(main, /1以上の整数を入力してください/);
  assert.match(main, /function validateFixedDocQrDelimiter/);
  assert.match(main, /区切り文字を入力してください/);
  assert.match(main, /getFixedDocQrDelimiterInput/);
  assert.match(main, /function validateFixedDocNormalConditionTarget/);
  assert.match(main, /最小値が最大値を超えています/);
  assert.match(main, /function revalidateAllFixedDocNormalConditions/);
  assert.doesNotMatch(main, /1〜\$\{total\}/);
  assert.match(main, /function resequenceAllFixedDocQrFetchIndexes/);
  assert.match(main, /function revalidateFixedDocQrSourceFetchIndexes/);
  assert.match(main, /function sortFixedDocQrSourceCatalog/);
  assert.match(main, /fixedDocQrSourceCatalog\.splice\(0, fixedDocQrSourceCatalog\.length\)/);
  assert.match(main, /clearFixedDocFieldQrSourceMappings\(sourceId\)/);
  assert.match(main, /clearFixedDocTableColumnQrSourceMappings\(sourceId\)/);
  assert.doesNotMatch(main, /function clearFixedDocQrSourceRegion\(sourceId\)/);
  assert.match(main, /fieldId: getFixedDocStableFieldId\(name\)/);
  assert.match(main, /fixedDocFieldRules\[row\.fieldId\]/);
  assert.match(main, /columnId: 'read-table-1-col-1'/);
  assert.match(main, /item\.columnId === columnRef/);
  assert.match(main, /label: 'AI読取設定'/);
  assert.match(main, /label: '処理ルール設定'/);
  assert.match(css, /\.fixed-doc-step-label\s*\{[^}]*white-space:\s*nowrap;/);
  assert.match(css, /\.fixed-doc-preview-canvas\s*\{[^}]*overflow:\s*hidden;/);
  assert.match(css, /\.fixed-doc-preview-canvas\s*\{[^}]*align-items:\s*center;/);
  assert.match(css, /\.fixed-doc-preview-stage\s*\{[^}]*width:\s*min\(100%, 520px\);/);
  // QR 設定ビュー撤去に伴うスタイルも削除済み（参照ゼロのセレクタを除去）
  assert.match(css, /\.fixed-doc-preview-hotspot\s*\{[\s\S]*border:\s*2px solid #175cd3;/);
  assert.match(css, /\.fixed-doc-preview-hotspot\.is-missing\s*\{[\s\S]*border-color:\s*#e31b54;/);
  assert.doesNotMatch(css, /\.fixed-doc-preview-region-draft/);
  assert.doesNotMatch(css, /\.fixed-doc-qr-source-/);
  assert.doesNotMatch(css, /\.fixed-doc-table-qr-/);
  assert.doesNotMatch(css, /\.fixed-doc-table--qr-read/);
  assert.doesNotMatch(css, /\.fixed-doc-read-mode-switch/);
  assert.doesNotMatch(css, /\.fixed-doc-type-readonly/);
  assert.doesNotMatch(css, /\.fixed-doc-test-source-label/);
  assert.match(css, /\.fixed-doc-range-input\.is-error \.el-input__wrapper,/);
  assert.match(main, /function onFixedDocPreviewWheel\(event\)/);
});
